name:{My Levels}
level-count:{49}
levels-beaten:{49}
show-hint:{true}
file-naming:{custom}
files:{
	zero-sum-game.lvl;
	the-disappearing-ledge.lvl;
	stuck-like-glue.lvl;
	progenitorial.lvl;
	open-the-bifrost.lvl;
	come-fly-with-me.lvl;
	the-stairs-to-heaven.lvl;
	et-tu-brute.lvl;
	the-floor-is-lava.lvl;
	the-expanse.lvl;
	light-stepper.lvl;
	the-great-pink-elevator.lvl;
	back-to-life.lvl;
	slip-and-slide.lvl;
	dont-weigh-me-down.lvl;
	catch-me-if-you-can.lvl;
	judgement-at-the-pearly-gates.lvl;
	turn-the-tables.lvl;
	the-spice-of-life.lvl;
	a-disappearing-act.lvl;
	walking-on-eggshells.lvl;
	the-pull-of-the-sea.lvl;
	a-fish-rots-from-the-head.lvl;
	the-two-aspects.lvl;
	separation-anxiety.lvl;
	the-overlap.lvl;
	the-intertidal-zone.lvl;
	downforce.lvl;
	generational-cowardice.lvl;
	up.lvl;
	the-fork-in-the-road.lvl;
	taxi-service.lvl;
	the-breeding-center.lvl;
	lost-in-space.lvl;
	the-great-dictator.lvl;
	splitsville.lvl;
	rally-race.lvl;
	engage-the-warp-drive.lvl;
	fever-dream-gondolier.lvl;
	an-undertaking.lvl;
	balloon-popping-lasers.lvl;
	an-expanding-universe.lvl;
	the-stairs-out-of-hell.lvl;
	bouncy-castle.lvl;
	the-nest.lvl;
	swimming-against-the-current.lvl;
	the-curse-of-the-necromancers.lvl;
	where-to-begin.lvl;
	liftoff.lvl
}
